# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:AWS_ORG}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: monitoring
# "service" is the name of this project. This will also be added to your AWS resource names.
service: monitoring

build:
  esbuild:
    bundle: true
    minify: false
    external:
      - 'pg'

custom:
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  environment:
      DATABASE_URL: ${env:DATABASE_URL}
      SUPABASE_URL: ${env:SUPABASE_URL}
      SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY}
      APIG_ENDPOINT:
        Fn::Join:
          - ''
          - - Ref: WebsocketsApi
            - .execute-api.
            - Ref: AWS::Region
            - .amazonaws.com/
            - ${self:custom.stage}

functions:
  api:
    handler: src/router.handler
    events:
      - httpApi: "*"
  websocket:
    handler: src/websocket.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $default
      - websocket:
          route: $disconnect
